### ISSUE TITLE
fix: 疎通 functions呼び出し時にエラーになっているっぽい

### ISSUE THREAD

**Issue by r-sugi** [r-sugi/nextjs-tdd-template#202]
functions呼び出し時にエラーになっている？

firebase  | >  {"severity":"ERROR","message":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:12618:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /opt/firebase/functions/lib/index.js:46:25\n    at async runFunction (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)\n    at async runBackground (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:517:5)\n    at async processBackground (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:501:5)\n    at async /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:690:21 {\n  cause: Error: connect ECONNREFUSED 127.0.0.1:8080\n      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {\n    errno: -111,\n    code: 'ECONNREFUSED',\n    syscall: 'connect',\n    address: '127.0.0.1',\n    port: 8080\n  }\n}"}

**Comment by r-sugi** [comment]
dockerからhostマシンに対して疎通しようとしていた。
